name: build
on:
  push:
    branches:
      - main

jobs:
  package_maintenance_job:
    name: A job to check Poetry project dependencies maintenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check dependencies maintenance
        id: package-maintenance
        uses: package-maintenance-dev/github-action@v0.0.1-SNAPSHOT
